<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Dignite.Site</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dignite.Site.Domain\Dignite.Site.Domain.csproj" />
    <ProjectReference Include="..\Dignite.Site.TestBase\Dignite.Site.TestBase.csproj" />
  </ItemGroup>


</Project>
