// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Files;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Files;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFilePublicAppService), typeof(FilePublicClientProxy))]
public partial class FilePublicClientProxy : ClientProxyBase<IFilePublicAppService>, IFilePublicAppService
{
    public virtual async Task<IRemoteStreamContent> GetAsync(string containerName, string blobName, GetFileInput input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), containerName },
            { typeof(string), blobName },
            { typeof(GetFileInput), input }
        });
    }
}
