// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Files;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Files;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFileAdminAppService), typeof(FileAdminClientProxy))]
public partial class FileAdminClientProxy : ClientProxyBase<IFileAdminAppService>, IFileAdminAppService
{
    public virtual async Task<FileDescriptorDto> GetAsync(Guid id)
    {
        return await RequestAsync<FileDescriptorDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<FileDescriptorDto>> GetListAsync(GetFilesInput input)
    {
        return await RequestAsync<PagedResultDto<FileDescriptorDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetFilesInput), input }
        });
    }

    public virtual async Task<FileDescriptorDto> CreateAsync(CreateFileInput input)
    {
        return await RequestAsync<FileDescriptorDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateFileInput), input }
        });
    }

    public virtual async Task<FileDescriptorDto> UpdateAsync(Guid id, UpdateFileInput input)
    {
        return await RequestAsync<FileDescriptorDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateFileInput), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<FileContainerConfigurationDto> GetContainerConfigurationAsync(string containerName)
    {
        return await RequestAsync<FileContainerConfigurationDto>(nameof(GetContainerConfigurationAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), containerName }
        });
    }
}
