// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Fields;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Fields;

public class CreateFieldDto
{
    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string FieldTypeName { get; set; }

    public string Description { get; set; }

    public Dictionary<string, object> Configuration { get; set; }

    public string GroupName { get; set; }
}
