// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Fields;
using Dignite.Site.Fields;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Fields;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFieldAdminAppService), typeof(FieldAdminClientProxy))]
public partial class FieldAdminClientProxy : ClientProxyBase<IFieldAdminAppService>, IFieldAdminAppService
{
    public virtual async Task<FieldDto> GetAsync(Guid id)
    {
        return await RequestAsync<FieldDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<FieldDto> FindByNameAsync(string name)
    {
        return await RequestAsync<FieldDto>(nameof(FindByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<ListResultDto<FieldDto>> GetListAsync(GetFieldListInput input)
    {
        return await RequestAsync<ListResultDto<FieldDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetFieldListInput), input }
        });
    }

    public virtual async Task<FieldDto> CreateAsync(CreateFieldDto input)
    {
        return await RequestAsync<FieldDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateFieldDto), input }
        });
    }

    public virtual async Task<FieldDto> UpdateAsync(Guid id, UpdateFieldDto input)
    {
        return await RequestAsync<FieldDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateFieldDto), input }
        });
    }

    public virtual async Task<FieldDto> RenameAsync(Guid id, RenameFieldDto input)
    {
        return await RequestAsync<FieldDto>(nameof(RenameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(RenameFieldDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<FieldTypeDto>> GetFieldTypesAsync()
    {
        return await RequestAsync<ListResultDto<FieldTypeDto>>(nameof(GetFieldTypesAsync));
    }
}
