// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Fields;
using Dignite.Site.Fields;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Fields;

public interface IFieldAdminAppService : IApplicationService
{
    Task<FieldDto> GetAsync(Guid id);

    Task<FieldDto> FindByNameAsync(string name);

    Task<ListResultDto<FieldDto>> GetListAsync(GetFieldListInput input);

    Task<FieldDto> CreateAsync(CreateFieldDto input);

    Task<FieldDto> UpdateAsync(Guid id, UpdateFieldDto input);

    Task<FieldDto> RenameAsync(Guid id, RenameFieldDto input);

    Task DeleteAsync(Guid id);

    Task<ListResultDto<FieldTypeDto>> GetFieldTypesAsync();
}
