// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.ContentTypes;
using Dignite.Site.ContentTypes;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.ContentTypes;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContentTypeAdminAppService), typeof(ContentTypeAdminClientProxy))]
public partial class ContentTypeAdminClientProxy : ClientProxyBase<IContentTypeAdminAppService>, IContentTypeAdminAppService
{
    public virtual async Task<ContentTypeDto> GetAsync(Guid id)
    {
        return await RequestAsync<ContentTypeDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<ContentTypeDto>> GetListByPageAsync(Guid pageId)
    {
        return await RequestAsync<ListResultDto<ContentTypeDto>>(nameof(GetListByPageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), pageId }
        });
    }

    public virtual async Task<ListResultDto<ContentTypeDto>> GetListAsync()
    {
        return await RequestAsync<ListResultDto<ContentTypeDto>>(nameof(GetListAsync));
    }

    public virtual async Task<ContentTypeDto> FindByNameAsync(Guid pageId, string name)
    {
        return await RequestAsync<ContentTypeDto>(nameof(FindByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), pageId },
            { typeof(string), name }
        });
    }

    public virtual async Task<ContentTypeDto> CreateAsync(CreateContentTypeDto input)
    {
        return await RequestAsync<ContentTypeDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateContentTypeDto), input }
        });
    }

    public virtual async Task<ContentTypeDto> UpdateAsync(Guid id, UpdateContentTypeDto input)
    {
        return await RequestAsync<ContentTypeDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateContentTypeDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
