// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.ContentTypes;
using Dignite.Site.ContentTypes;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.ContentTypes;

public interface IContentTypeAdminAppService : IApplicationService
{
    Task<ContentTypeDto> GetAsync(Guid id);

    Task<ContentTypeDto> FindByNameAsync(Guid pageId, string name);

    Task<ListResultDto<ContentTypeDto>> GetListByPageAsync(Guid pageId);

    Task<ListResultDto<ContentTypeDto>> GetListAsync();

    Task<ContentTypeDto> CreateAsync(CreateContentTypeDto input);

    Task<ContentTypeDto> UpdateAsync(Guid id, UpdateContentTypeDto input);

    Task DeleteAsync(Guid id);
}
