// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.ContentTypes;
using Dignite.Site.ContentTypes;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.ContentTypes;

public class UpdateContentTypeDto
{
    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Description { get; set; }

    public ContentTypeFieldDto[] Fields { get; set; }
}
