// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Fields;
using Dignite.Site.Public.Fields;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Fields;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFieldPublicAppService), typeof(FieldPublicClientProxy))]
public partial class FieldPublicClientProxy : ClientProxyBase<IFieldPublicAppService>, IFieldPublicAppService
{
    public virtual async Task<FieldDto> GetAsync(Guid id)
    {
        return await RequestAsync<FieldDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<FieldDto>> GetListAsync(IEnumerable<Guid> ids)
    {
        return await RequestAsync<ListResultDto<FieldDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IEnumerable<Guid>), ids }
        });
    }
}
