// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Fields;
using Dignite.Site.Public.Fields;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Fields;

public interface IFieldPublicAppService : IApplicationService
{
    Task<FieldDto> GetAsync(Guid id);

    Task<ListResultDto<FieldDto>> GetListAsync(IEnumerable<Guid> ids);
}
