using System;
using Volo.Abp;
using Volo.Abp.Auditing;
using Volo.Abp.Domain.Entities;
using Volo.Abp.MultiTenancy;

namespace Dignite.Site.Files;

/// <summary>
/// One file in Site's file library: the record of a blob that <c>IFileStorer</c> put into one of the
/// <see cref="SiteFileContainerNames"/> containers, plus where an editor filed it.
/// <para>
/// <b>Content dedup.</b> Uploading bytes that are already stored in the same container (same tenant) does
/// not keep a second copy: the new descriptor is a <i>reference</i> - its <see cref="ReferBlobName"/> names
/// the blob that holds the bytes, and its own <see cref="BlobName"/> is only its address. Only the owner of
/// a blob carries its <see cref="Hash"/>. <see cref="FileDescriptorManager"/> decides both, and deletes a
/// blob only once no live descriptor refers to it.
/// </para>
/// </summary>
public class FileDescriptor : AggregateRoot<Guid>, ICreationAuditedObject, IDeletionAuditedObject, IMultiTenant
{
    protected FileDescriptor()
    {
    }

    public FileDescriptor(
        Guid id,
        string containerName,
        string blobName,
        string name,
        string mimeType,
        long size,
        string? hash,
        string? referBlobName,
        Guid? directoryId,
        Guid? tenantId)
        : base(id)
    {
        ContainerName = Check.NotNullOrWhiteSpace(containerName, nameof(containerName), FileDescriptorConsts.MaxContainerNameLength);
        BlobName = Check.NotNullOrWhiteSpace(blobName, nameof(blobName), FileDescriptorConsts.MaxBlobNameLength);
        Name = Check.NotNullOrWhiteSpace(name, nameof(name), FileDescriptorConsts.MaxNameLength);
        MimeType = Check.Length(mimeType, nameof(mimeType), FileDescriptorConsts.MaxMimeTypeLength) ?? string.Empty;
        Size = size;
        Hash = Check.Length(hash, nameof(hash), FileDescriptorConsts.MaxHashLength) ?? string.Empty;
        ReferBlobName = Check.Length(referBlobName, nameof(referBlobName), FileDescriptorConsts.MaxBlobNameLength) ?? string.Empty;
        DirectoryId = directoryId;
        TenantId = tenantId;
    }

    public virtual string ContainerName { get; protected set; } = default!;

    /// <summary>
    /// The descriptor's own address in its container (<c>/api/site-public/files/{container}/{BlobName}</c>).
    /// Generated by the container's blob name generator, never chosen by a caller, and never reused.
    /// </summary>
    public virtual string BlobName { get; protected set; } = default!;

    /// <summary>The size of the stored bytes, after the container's upload handlers ran.</summary>
    public virtual long Size { get; protected set; }

    /// <summary>The display name - the uploader's file name, which an editor may change.</summary>
    public virtual string Name { get; protected set; } = default!;

    /// <summary>Detected from the stored content (<c>IMimeTypeDetector</c>), never the uploader's claim.</summary>
    public virtual string MimeType { get; protected set; } = default!;

    /// <summary>
    /// SHA-256 of the stored bytes (<c>StoredFileInfo.Hash</c>), on the blob's owner only; empty on a
    /// reference. Unique per tenant and container among the live descriptors - the arbiter of dedup.
    /// </summary>
    public virtual string Hash { get; protected set; } = string.Empty;

    /// <summary>
    /// When not empty, this descriptor is a reference: the bytes live in the blob of this name, which
    /// another descriptor owns (or owned - a deleted owner's blob stays while references to it remain).
    /// </summary>
    public virtual string ReferBlobName { get; protected set; } = string.Empty;

    /// <summary>The directory the file is filed in, or <c>null</c> for the container's root.</summary>
    public virtual Guid? DirectoryId { get; protected set; }

    public virtual DateTime CreationTime { get; set; }

    public virtual Guid? CreatorId { get; set; }

    public virtual Guid? DeleterId { get; set; }

    public virtual DateTime? DeletionTime { get; set; }

    public virtual bool IsDeleted { get; set; }

    public virtual Guid? TenantId { get; protected set; }

    /// <summary>Whether the bytes are another descriptor's blob (see <see cref="ReferBlobName"/>).</summary>
    public virtual bool IsReference()
    {
        return !ReferBlobName.IsNullOrEmpty();
    }

    /// <summary>The blob that actually holds this file's bytes.</summary>
    public virtual string GetActualBlobName()
    {
        return IsReference() ? ReferBlobName : BlobName;
    }

    public virtual void Rename(string name)
    {
        Name = Check.NotNullOrWhiteSpace(name, nameof(name), FileDescriptorConsts.MaxNameLength);
    }

    /// <summary>
    /// Files the descriptor under <paramref name="directoryId"/> (<c>null</c> for the root). Whether that
    /// directory may hold it - same container, owner and tenant - is checked by the caller.
    /// </summary>
    public virtual void MoveToDirectory(Guid? directoryId)
    {
        DirectoryId = directoryId;
    }
}
