// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Schema;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Schema;

public interface ISiteSchemaAdminAppService : IApplicationService
{
    Task<SiteSchemaDto> GetAsync();
}
