// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Schema;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Schema;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISiteSchemaAdminAppService), typeof(SiteSchemaAdminClientProxy))]
public partial class SiteSchemaAdminClientProxy : ClientProxyBase<ISiteSchemaAdminAppService>, ISiteSchemaAdminAppService
{
    public virtual async Task<SiteSchemaDto> GetAsync()
    {
        return await RequestAsync<SiteSchemaDto>(nameof(GetAsync));
    }
}
