// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Schema;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Schema;

public class SiteSchemaDto
{
    public string[] EnabledLanguages { get; set; }

    public string DefaultLanguage { get; set; }

    public string PrimaryDomain { get; set; }

    public SiteSchemaPageDto[] Pages { get; set; }
}
