// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Schema;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Schema;

public class SiteSchemaPageDto
{
    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Route { get; set; }

    public bool IsHomePage { get; set; }

    public bool IsActive { get; set; }

    public string Parent { get; set; }

    public SiteSchemaContentTypeDto[] ContentTypes { get; set; }
}
