// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Pages;
using Dignite.Site.Public.Pages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Pages;

public interface IPagePublicAppService : IApplicationService
{
    Task<PageDto> GetAsync(Guid id);

    Task<PageDto> GetByRouteAsync(string route);

    Task<PageDto> FindByNameAsync(string name);

    Task<ListResultDto<PageDto>> GetListAsync(GetPageListInput input);
}
