// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Pages;
using Dignite.Site.Public.Pages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Pages;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPagePublicAppService), typeof(PagePublicClientProxy))]
public partial class PagePublicClientProxy : ClientProxyBase<IPagePublicAppService>, IPagePublicAppService
{
    public virtual async Task<PageDto> GetAsync(Guid id)
    {
        return await RequestAsync<PageDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PageDto> GetByRouteAsync(string route)
    {
        return await RequestAsync<PageDto>(nameof(GetByRouteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), route }
        });
    }

    public virtual async Task<PageDto> FindByNameAsync(string name)
    {
        return await RequestAsync<PageDto>(nameof(FindByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<ListResultDto<PageDto>> GetListAsync(GetPageListInput input)
    {
        return await RequestAsync<ListResultDto<PageDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPageListInput), input }
        });
    }
}
