// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Contents;
using Dignite.Site.Public.Contents;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Contents;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContentPublicAppService), typeof(ContentPublicClientProxy))]
public partial class ContentPublicClientProxy : ClientProxyBase<IContentPublicAppService>, IContentPublicAppService
{
    public virtual async Task<ContentDto> GetAsync(Guid id)
    {
        return await RequestAsync<ContentDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ContentDto> GetBySlugAsync(Guid pageId, string cultureName, string slug)
    {
        return await RequestAsync<ContentDto>(nameof(GetBySlugAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), pageId },
            { typeof(string), cultureName },
            { typeof(string), slug }
        });
    }

    public virtual async Task<PagedResultDto<ContentDto>> GetListAsync(GetContentListInput input)
    {
        return await RequestAsync<PagedResultDto<ContentDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetContentListInput), input }
        });
    }

    public virtual async Task<ListResultDto<ContentDto>> GetTranslationsAsync(Guid pageId, Guid contentTypeId, string slug)
    {
        return await RequestAsync<ListResultDto<ContentDto>>(nameof(GetTranslationsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), pageId },
            { typeof(Guid), contentTypeId },
            { typeof(string), slug }
        });
    }
}
