// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Contents;
using Dignite.Site.Public.Contents;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Contents;

public interface IContentPublicAppService : IApplicationService
{
    Task<ContentDto> GetBySlugAsync(Guid pageId, string cultureName, string slug);

    Task<ListResultDto<ContentDto>> GetTranslationsAsync(Guid pageId, Guid contentTypeId, string slug);

    Task<ContentDto> GetAsync(Guid id);

    Task<PagedResultDto<ContentDto>> GetListAsync(GetContentListInput input);
}
