// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.ContentTypes;
using Dignite.Site.Public.ContentTypes;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.ContentTypes;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContentTypePublicAppService), typeof(ContentTypePublicClientProxy))]
public partial class ContentTypePublicClientProxy : ClientProxyBase<IContentTypePublicAppService>, IContentTypePublicAppService
{
    public virtual async Task<ContentTypeDto> GetAsync(Guid id)
    {
        return await RequestAsync<ContentTypeDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<ContentTypeDto>> GetListByPageAsync(Guid pageId)
    {
        return await RequestAsync<ListResultDto<ContentTypeDto>>(nameof(GetListByPageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), pageId }
        });
    }
}
