// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.ContentTypes;
using Dignite.Site.Public.ContentTypes;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.ContentTypes;

public interface IContentTypePublicAppService : IApplicationService
{
    Task<ContentTypeDto> GetAsync(Guid id);

    Task<ListResultDto<ContentTypeDto>> GetListByPageAsync(Guid pageId);
}
