<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Dignite.Site.Admin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="10.5.0"/>
    <ProjectReference Include="..\Dignite.Site.Admin.Application.Contracts\Dignite.Site.Admin.Application.Contracts.csproj" />
    <ProjectReference Include="..\Dignite.Site.Common.HttpApi\Dignite.Site.Common.HttpApi.csproj" />
  </ItemGroup>

</Project>
