// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Pages;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Pages;

public class CreatePageDto
{
    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Route { get; set; }

    public string Template { get; set; }

    public string ContentTemplate { get; set; }

    public Guid? ParentId { get; set; }

    public bool IsActive { get; set; }
}
