// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Pages;
using Dignite.Site.Pages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Pages;

public interface IPageAdminAppService : IApplicationService
{
    Task<PageDto> GetAsync(Guid id);

    Task<PageDto> FindByNameAsync(string name);

    Task<ListResultDto<PageDto>> GetListAsync(GetPageListInput input);

    Task<PageDto> CreateAsync(CreatePageDto input);

    Task<PageDto> UpdateAsync(Guid id, UpdatePageDto input);

    Task DeleteAsync(Guid id);
}
