// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Pages;
using Dignite.Site.Pages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Pages;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPageAdminAppService), typeof(PageAdminClientProxy))]
public partial class PageAdminClientProxy : ClientProxyBase<IPageAdminAppService>, IPageAdminAppService
{
    public virtual async Task<PageDto> GetAsync(Guid id)
    {
        return await RequestAsync<PageDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PageDto> FindByNameAsync(string name)
    {
        return await RequestAsync<PageDto>(nameof(FindByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<ListResultDto<PageDto>> GetListAsync(GetPageListInput input)
    {
        return await RequestAsync<ListResultDto<PageDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPageListInput), input }
        });
    }

    public virtual async Task<PageDto> CreateAsync(CreatePageDto input)
    {
        return await RequestAsync<PageDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreatePageDto), input }
        });
    }

    public virtual async Task<PageDto> UpdateAsync(Guid id, UpdatePageDto input)
    {
        return await RequestAsync<PageDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdatePageDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
