// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Routing;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Routing;

public interface IRoutingPublicAppService : IApplicationService
{
    Task<RouteMatchDto> ResolveAsync(ResolvePathInput input);
}
