// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Routing;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Routing;

public class ResolvePathInput
{
    public string Path { get; set; }
}
