// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Contents;
using Dignite.Site.ContentTypes;
using Dignite.Site.Pages;
using Dignite.Site.Public.Routing;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Routing;

public class RouteMatchDto
{
    public bool Matched { get; set; }

    public RouteMatchKindDto Kind { get; set; }

    public string CultureName { get; set; }

    public PageDto Page { get; set; }

    public ContentDto Content { get; set; }

    public ContentTypeDto ContentType { get; set; }

    public Dictionary<string, string> FilterValues { get; set; }
}
