// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Routing;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Routing;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IRoutingPublicAppService), typeof(RoutingPublicClientProxy))]
public partial class RoutingPublicClientProxy : ClientProxyBase<IRoutingPublicAppService>, IRoutingPublicAppService
{
    public virtual async Task<RouteMatchDto> ResolveAsync(ResolvePathInput input)
    {
        return await RequestAsync<RouteMatchDto>(nameof(ResolveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResolvePathInput), input }
        });
    }
}
