// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Seo;
using Dignite.Site.Seo;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Seo;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFeedDocumentAppService), typeof(FeedDocumentPublicClientProxy))]
public partial class FeedDocumentPublicClientProxy : ClientProxyBase<IFeedDocumentAppService>, IFeedDocumentAppService
{
    public virtual async Task<SiteDocument> GetAsync(string pagePath, string cultureName, SiteFeedFormat format)
    {
        return await RequestAsync<SiteDocument>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), pagePath },
            { typeof(string), cultureName },
            { typeof(SiteFeedFormat), format }
        });
    }

    public virtual async Task<SiteDocument> ResolveAsync(string feedPath)
    {
        return await RequestAsync<SiteDocument>(nameof(ResolveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), feedPath }
        });
    }
}
