// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Seo;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Seo;

public class HeadMetadataDto
{
    public string MetaTitle { get; set; }

    public string MetaDescription { get; set; }

    public string CanonicalUrl { get; set; }

    public string RobotsContent { get; set; }

    public string OgImageUrl { get; set; }

    public string OgType { get; set; }

    public string TwitterCardType { get; set; }

    public HreflangAlternateDto[] HreflangAlternates { get; set; }

    public string XDefaultUrl { get; set; }
}
