// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Seo;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Seo;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IHeadMetadataPublicAppService), typeof(HeadMetadataPublicClientProxy))]
public partial class HeadMetadataPublicClientProxy : ClientProxyBase<IHeadMetadataPublicAppService>, IHeadMetadataPublicAppService
{
    public virtual async Task<HeadMetadataDto> ResolveAsync(ResolveHeadMetadataInput input)
    {
        return await RequestAsync<HeadMetadataDto>(nameof(ResolveAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ResolveHeadMetadataInput), input }
        });
    }
}
