// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Seo;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Seo;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IRobotsDocumentAppService), typeof(RobotsDocumentPublicClientProxy))]
public partial class RobotsDocumentPublicClientProxy : ClientProxyBase<IRobotsDocumentAppService>, IRobotsDocumentAppService
{
    public virtual async Task<SiteDocument> GetRobotsTxtAsync()
    {
        return await RequestAsync<SiteDocument>(nameof(GetRobotsTxtAsync));
    }

    public virtual async Task<SiteDocument> GetLlmsTxtAsync()
    {
        return await RequestAsync<SiteDocument>(nameof(GetLlmsTxtAsync));
    }
}
