// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Public.Seo;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Public.Seo;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISitemapDocumentAppService), typeof(SitemapDocumentPublicClientProxy))]
public partial class SitemapDocumentPublicClientProxy : ClientProxyBase<ISitemapDocumentAppService>, ISitemapDocumentAppService
{
    public virtual async Task<SiteDocument> GetIndexAsync()
    {
        return await RequestAsync<SiteDocument>(nameof(GetIndexAsync));
    }

    public virtual async Task<SiteDocument> GetShardAsync(int shardNumber)
    {
        return await RequestAsync<SiteDocument>(nameof(GetShardAsync), new ClientProxyRequestTypeValue
        {
            { typeof(int), shardNumber }
        });
    }
}
