<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Dignite.Sites</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client" Version="10.5.0"/>
    <ProjectReference Include="..\Dignite.Sites.Application.Contracts\Dignite.Sites.Application.Contracts.csproj" />
    <ProjectReference Include="..\Dignite.Sites.Admin.HttpApi.Client\Dignite.Sites.Admin.HttpApi.Client.csproj" />
    <ProjectReference Include="..\Dignite.Sites.Public.HttpApi.Client\Dignite.Sites.Public.HttpApi.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*generate-proxy.json" />
    <Content Remove="**\*generate-proxy.json" />
  </ItemGroup>

</Project>
