// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Contents;
using Dignite.Site.Contents;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Contents;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContentAdminAppService), typeof(ContentAdminClientProxy))]
public partial class ContentAdminClientProxy : ClientProxyBase<IContentAdminAppService>, IContentAdminAppService
{
    public virtual async Task<ContentDto> GetAsync(Guid id)
    {
        return await RequestAsync<ContentDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ContentDto> FindBySlugAsync(Guid pageId, string cultureName, string slug)
    {
        return await RequestAsync<ContentDto>(nameof(FindBySlugAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), pageId },
            { typeof(string), cultureName },
            { typeof(string), slug }
        });
    }

    public virtual async Task<PagedResultDto<ContentDto>> GetListAsync(GetContentListInput input)
    {
        return await RequestAsync<PagedResultDto<ContentDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetContentListInput), input }
        });
    }

    public virtual async Task<ContentDto> CreateAsync(CreateContentDto input)
    {
        return await RequestAsync<ContentDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateContentDto), input }
        });
    }

    public virtual async Task<ContentDto> UpdateAsync(Guid id, UpdateContentDto input)
    {
        return await RequestAsync<ContentDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateContentDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
