// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Abp.FlexFields;
using Dignite.Site.Admin.Contents;
using Dignite.Site.Contents;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Contents;

public class GetContentListInput : PagedAndSortedResultRequestDto
{
    public Guid? PageId { get; set; }

    public string CultureName { get; set; }

    public Guid? ContentTypeId { get; set; }

    public ContentStatus? Status { get; set; }

    public DateTime? PublishedBefore { get; set; }

    public DateTime? PublishedAfter { get; set; }

    public string Filter { get; set; }

    public FlexFieldQueryCondition[] FlexFieldConditions { get; set; }
}
