// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Contents;
using Dignite.Site.Contents;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Contents;

public interface IContentAdminAppService : IApplicationService
{
    Task<ContentDto> FindBySlugAsync(Guid pageId, string cultureName, string slug);

    Task<ContentDto> GetAsync(Guid id);

    Task<PagedResultDto<ContentDto>> GetListAsync(GetContentListInput input);

    Task<ContentDto> CreateAsync(CreateContentDto input);

    Task<ContentDto> UpdateAsync(Guid id, UpdateContentDto input);

    Task DeleteAsync(Guid id);
}
