// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.Site.Admin.Contents;
using Dignite.Site.Contents;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Dignite.Site.Admin.Contents;

public class UpdateContentDto
{
    public string Slug { get; set; }

    public DateTime PublishTime { get; set; }

    public ContentStatus Status { get; set; }

    public Dictionary<string, object> FieldValues { get; set; }

    public Guid? ContentTypeId { get; set; }
}
