<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Dignite.Site</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Mapperly" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.5.0" />
    <ProjectReference Include="..\Dignite.Site.Application.Contracts\Dignite.Site.Application.Contracts.csproj" />
    <ProjectReference Include="..\Dignite.Site.Admin.Application\Dignite.Site.Admin.Application.csproj" />
    <ProjectReference Include="..\Dignite.Site.Public.Application\Dignite.Site.Public.Application.csproj" />
  </ItemGroup>

</Project>
